const counterActionTypes = {
    COUNTER_INCREMENT: 'COUNTER_INCREMENT',
    COUNTER_INCREMENT_ASYNC: 'COUNTER_INCREMENT_ASYNC',
    COUNTER_DECREMENT: 'COUNTER_DECREMENT',
    COUNTER_INCREMENT_BY_AMOUNT: 'COUNTER_INCREMENT_BY_AMOUNT',
}

export default counterActionTypes;